### ISSUE TITLE
Jam high-order title is repetitive

### ISSUE THREAD

**Issue by vintprox** [OneHourGameJam/OneHourGameJam#100]
Theme authenticity falls apart near long high-order title of the jam.

![screenshot_2019-01-07-22-22-59](https://user-images.githubusercontent.com/5708819/50789644-ea4cad00-12cd-11e9-92c0-1ac2eca0767b.png)

## TL;DR:

Make jam header not have text like this:
```
] 192nd one hour game jam (29 Dec 2018)
] Theme: Shopkeeper OR Can't Stop
] Started: 29 Dec 2018 at 20:00 (13 entries)
```
But instead make it have this:
```
] Shopkeeper OR Can't stop :: #192
] 192nd one hour game jam (29 Dec 2018) 
] Started 12/29/2018 at 20:00. Now has 13 entries.
```

## Details, Skipper?

Look, `one hour game jam` part is truly repetitive. User must have already gotten that they're dealing with 1 hour gamejams.

This legacy `*nd one hour game jam (DATE)` title though could be placed on the 2nd row instead of theme name.

And theme name is more likely the primary identity of any unique jam, so it should be placed on the 1st row as high-ordered title.

**Comment by vintprox** [comment]
So, that's what it can appear like:

![screenshot_2019-01-08-11-01-56](https://user-images.githubusercontent.com/5708819/50817449-e607aa80-1334-11e9-9529-d27cfd3f28d1.png)

**Comment by mkalam-alami** [comment]
What about:

![2019-01-08 11_44_22-one hour game jam - main page](https://user-images.githubusercontent.com/694508/50825994-cd01f800-133a-11e9-8845-767de5f195e3.png)

**Comment by vintprox** [comment]
@mkalam-alami I'll sign under this design! Your's actually better.

**Comment by Denneledoe** [comment]
100th issue!
