### ISSUE TITLE
Some characters display incorrectly

### ISSUE THREAD

**Issue by pta2002** [OneHourGameJam/OneHourGameJam#12]
On some titles, some characters show up as the HTML escape code, not the character itself.

**Comment by lucasdealmeidasm** [comment]
Which ones?

**Comment by pta2002** [comment]
I am not sure which ones, but I found this when I was looking through some
jams. For example, (I don't know which) characters show up like this:
(&000;) (of course not with 000). I found some on the 'Rock Simulator' jam

**Comment by balohmatevz** [comment]
Fixed in 28031d51832634cdb0d6e9ff6a08e2aec190e94c
