### ISSUE TITLE
Add a "this site uses cookies" thing somewhere

### ISSUE THREAD

**Issue by liambaloh** [OneHourGameJam/OneHourGameJam#137]
Apparently that broke at some point. I think the only cookies used by the site are whether or not the user is in dark mode and their session cookie. So the popup should only appear when these features are required and not on first visit.

**Comment by mkalam-alami** [comment]
FYI the GDPR should not require any specific mention for session cookies: 

> Consent is not required if the cookie is:
> * used for the sole purpose of carrying out the transmission of a communication, and
> * strictly necessary in order for the provider of an information society service explicitly required by the user to provide that service.

(Source: http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm#section_2)

It seems like "remember me" cookies are usually considered to fall into these exceptions. I suspect the "dark mode" fits as well as it's a purely functional thing, but in the worst case we could always store a user preference over a cookie.
