### ISSUE TITLE
Make poll obey dark theme

### ISSUE THREAD

**Issue by adamtpowell** [OneHourGameJam/OneHourGameJam#160]
![image](https://user-images.githubusercontent.com/43593885/52903665-d5c5d380-31ee-11e9-9d09-5030e067eecd.png)

Currently, the poll styling ignores the preference for a dark theme. It should be changed the rest of the dark theme styling.

**Comment by liambaloh** [comment]
I couldn't find a nice color for it... Any suggestions?
