### ISSUE TITLE
Indicate number of entries

### ISSUE THREAD

**Issue by WetDesertRock** [OneHourGameJam/OneHourGameJam#17]
This is a suggestion to indicate the number of jam entries in the header for the jam. Maybe something like:
```
30th hour game jam, 120 participants 
Theme: Spam Bots
Started: 01 Jan 1870 at 01:00
```

**Comment by balohmatevz** [comment]
Fixed in 7a33d32d4f5b55ff15886c8e54c5ccaa42001e82
