### ISSUE TITLE
Allow users to change a forgotten password

### ISSUE THREAD

**Issue by Raccoon-JS** [OneHourGameJam/OneHourGameJam#171]
I forgot my password, and I can't get in. I tried to find "forgot password" link in Log In page but there is none. What should I do if I can't find one? Can Admin delete my old account?

Can you make the "forgot password" link so I could reset it after going through user validations?

**Comment by mkalam-alami** [comment]
Until a full "forgotten password" thing gets made, a quick backup thing would be to:

1. Make email mandatory when creating the account
2. Make the "Forgot password" link lead to a short page suggesting to ask the admins on Discord
3. The admins would set a temporary password and send to the registered email

**Comment by LongarMD** [comment]
I was thinking about the same thing as your 2nd and 3rd point.
AFAIK we're currently not storing emails because of a security concern (cc @liambaloh ) so we'd need to find a workaround if we didn't want to use emails. Using emails would also require us to set up an email server.

**Comment by liambaloh** [comment]
We just share the new password to the user via Discord 🤷‍♀

Email addresses are personal information, so I'd prefer to not have to force anyone to provide it, as we really don't care who anyone is in real life - there's no benefit at all to us knowing that. 

Then again, storing email addresses would allow us to implement things like jam reminders via email, password resetting, security breach notifications, privacy policy update notifications, etc. We could become more like NetLog or Bebo or some other service you used to love but now only interact with when they send you terms of service update emails! 😄

So i guess I have a preference to keep providing email addresses as opt-in. Even though at this moment in time we don't actually _do_ anything at all with those email addresses. 

Also: We have an email server set up

**Comment by mkalam-alami** [comment]
Most of the time it's not a big concern, but technically you can't know for sure that a guy on Discord is the owner of the 1HGJ account, unless you have a field somewhere on the site to fill the Discord handle. That's why I was suggesting the email as a reliable way to share sensitive data.

More importantly, the email server cannot send a reset link if it has no email to send it to.

If not mandatory I would at least leave a note near the email field in the user settings, like "recommended for account recovery purposes".

**Comment by LongarMD** [comment]
I added a Forgot Password? page that refers the user to the Discord server.
Since it seems like adding an email field to the user registration would require a separate discussion (and issue) I am closing this issue. Feel free to reopen it if you disagree.
