### ISSUE TITLE
Add a separate page for creating accounts

### ISSUE THREAD

**Issue by puarsliburf** [OneHourGameJam/OneHourGameJam#175]
The current system where a new account is created if you try to sign in with one that doesn't exist is confusing and can (and has) lead to accounts being created on accident when people misspell their usernames.

I think we should add a new page for account creation and simply display an error if you try to login to a non-existent account.

**Comment by liambaloh** [comment]
Possible easier implementation is to add an interim step which has users confirm the creation of the account. So users who didn't intend to create an account can back out then.

So registration looks like:
Login [username & password fields like now] -> User [username] doesn't exist yet, would you like it to be created? [Yes button pressed] -> Logged in \o/

And misspelled usernames:
Login [misspelled username & password] -> User [username] doesn't exist yet, would you like it to be created? [No! Back out!] -> Login [username & password] -> Logged in \o/
