### ISSUE TITLE
CSRF error on theme submission

### ISSUE THREAD

**Issue by LongarMD** [OneHourGameJam/OneHourGameJam#176]
[From @Enoxis#1850 over Discord:
](https://discordapp.com/channels/285133441937440770/285133441937440770/668500359034961962)
> Potential CSRF Detected. If you made this request from the website, please contact the site admin.
If you are a developer, add {{> csrf_token}} to the form you just submitted!
> I got this error suggesting a theme

**Comment by liambaloh** [comment]
Nothing similar has been reported in 7 months. This makes me think it was a bit of a fluke or something messing with the php session id cookie client-side. If something comes up again we can look into it again, but until then I don't think there's a reason to keep this open...
