### ISSUE TITLE
submitting a banned theme does not give adequate feedback

### ISSUE THREAD

**Issue by Denneledoe** [OneHourGameJam/OneHourGameJam#177]
right now it shows up as:
"theme already suggested"

https://gyazo.com/a6b6d9eb4eeb232f72632e94e0bedd69

should probably say something about the thing being banned

**Comment by liambaloh** [comment]
Should be easy enough to do: add an isbanned check to before where "THEME_ALREADY_SUGGESTED" is returned in https://github.com/OneHourGameJam/OneHourGameJam/blob/master/php/actions/theme/savenewtheme.php#L21 and return some new descriptive string identifier instead, and then add it to the list of site action responses here: https://github.com/OneHourGameJam/OneHourGameJam/blob/master/php/models/SiteActionModel.php
