### ISSUE TITLE
Asset submission

### ISSUE THREAD

**Issue by matt-b-1hgj** [OneHourGameJam/OneHourGameJam#19]
It'd be nice to have something for submitting assets, maybe like the entry submission page with a link to the asset file & a thumbnail, hosted by the uploader. Some of the good general purpose assets could be hosted onsite, like the ones bitslap shared.

Feature could be admin only or open to all users.

**Comment by CrazyMatt** [comment]
This sounds like a good idea. It would also be nice to make the assets searchable.
