### ISSUE TITLE
Clock gets out of sync

### ISSUE THREAD

**Issue by balohmatevz** [OneHourGameJam/OneHourGameJam#20]
After a while, the javascript clock in the top right gets out of sync.

Needs to be changed from setTimeout(..,1000) to something based on current vs target time.

**Comment by MikeDX** [comment]
Whoever wrote it that way needs shooting ;)

**Comment by balohmatevz** [comment]
Ok, thanks. Glad to see this comment was your only contribution.

**Comment by MikeDX** [comment]
Not true!

Anyway I may submit a pull request to fix this at the weekend :)

**Comment by balohmatevz** [comment]
Great. Until then (and after too), please don't insult existing contributions or their authors.

**Comment by MikeDX** [comment]
Ok

Firstly, i am already a contributor to one hour game jam in multiple ways, including having submitted merged pull requests in the past amongst other things.

Second, get off your high horse. It was clearly intended as a tongue in cheek remark.
