### ISSUE TITLE
Ability to search by theme

### ISSUE THREAD

**Issue by CrazyMatt** [OneHourGameJam/OneHourGameJam#22]
In the 1HGJ Search bar, you should be able to search by theme. That is, if you searched for "Deeper and Deeper", the games of 1HGJ 2 should appear.

**Comment by balohmatevz** [comment]
Added this ability on the jams list page: http://onehourgamejam.com/?page=jams

**Comment by balohmatevz** [comment]
Added in https://github.com/OneHourGameJam/OneHourGameJam/commit/4aa519965eff8988cb49885b4a0410b8c3d54b64
