### ISSUE TITLE
Ability to edit old entries

### ISSUE THREAD

**Issue by Gaximaran** [OneHourGameJam/OneHourGameJam#28]
A possibility to edit old entries would be wonderful. Many of my entries either have lost their screenshot, or it is impossible to download them.

**Comment by mkalam-alami** [comment]
I'd like to have this too!

@balohmatevz Do I have your blessing to try and implement this?

**Comment by balohmatevz** [comment]
You don't need my blessing to help :D

**Comment by mkalam-alami** [comment]
Done! See PR #35

**Comment by CrazyMatt** [comment]
Perhaps there should be an edit history viewable by admins?

**Comment by balohmatevz** [comment]
I've added a rudimentary version of this through MySQL triggers in https://github.com/OneHourGameJam/OneHourGameJam/commit/af1f92e8decd338d21133fbefde24dd8cf3f2526

Currently it can only be viewed by the database admin, however a page can be added to the admin tools if anyone wants to do that (possibly just a raw output of this new entry_changelog table would suffice).
