### ISSUE TITLE
Clean install does not promote first user to admin

### ISSUE THREAD

**Issue by MikeDX** [OneHourGameJam/OneHourGameJam#31]
As per title, installing OHGJ from github (master / aff3295d88785acc00d8ce3f4bb5952e6f2c06c5 ), importing SQL to mysql, configuring DB and running does not give first user access to any admin settings, which have to be set manually in db/user/user_role)

Steps to reproduce:

`git clone https://github.com/OneHourGameJam/OneHourGameJam/`
`cd OneHourGameJam`

install DB, load SQL from SQL/1hgj.sql *

edit config/db.php with database info

`php -S localhost:8080`

open browser to localhost:8080

login/register with any user / pass

see no admin privileges. Schedule no jams.

**Comment by balohmatevz** [comment]
Probably an oversight from when the codebase was moved from using json files to using the database. Thank you for reporting this.
