### ISSUE TITLE
Next jam date / time incorrect

### ISSUE THREAD

**Issue by MikeDX** [OneHourGameJam/OneHourGameJam#32]
Future jam date (top right corner) seems to be incorrectly hardcoded, scheduling a jam does not show the correct date and time.

in php/helpers.php, GetNextJamDateAndTime() function sets next_jam_suggested_time to saturday +20 hours.

![screenshot from 2016-11-19 10-40-14](https://cloud.githubusercontent.com/assets/853931/20454883/94c136ac-ae44-11e6-8827-18f19211a86c.png)

**Comment by balohmatevz** [comment]
Oh yeah, I forgot about this. I think it's similar in the code that determines the default time for the next jam (the pre-filled values in the date and time entries in the "schedule new jam" screen.) Thank you for reporting this.

**Comment by balohmatevz** [comment]
This one now works off of the data in config, it however does not work if a jam is scheduled at a non-standard time.
