### ISSUE TITLE
Database versioning and automatic upgrading

### ISSUE THREAD

**Issue by liambaloh** [OneHourGameJam/OneHourGameJam#43]
The database structure changes every so often. To make site upgrades easier, an automated system for DB upgrades should probably exist - something which simply updates the database with ALTER, CREATE and DROP statements as needed between versions. 

(Low priority feature)

**Comment by vintprox** [comment]
Migrations is the good concept for MySQL+PHP stack

**Comment by balohmatevz** [comment]
There is currently a folder of migration scripts located here: https://github.com/OneHourGameJam/OneHourGameJam/tree/master/SQL/migrations

But these must be executed manually and there isn't a good way to determine which ones you need to execute to get from the version you're on to the most recent one...

**Comment by vintprox** [comment]
There should be some order of these scripts, preferably self-explanatory (via placing queue number in file name), e.g. without additional meta file

**Comment by balohmatevz** [comment]
The plan at the moment is to tie a migration file to a version, stored in config and compare it to a constant number somewhere in code. If the two don't match, migration scripts are ran. But that's not in the code yet, so you have to do it manually.

**Comment by winniehell** [comment]
@liambaloh woul using https://flywaydb.org/ be an option? It uses a structure similar to the one that already exists in the SQL directory here.

**Comment by liambaloh** [comment]
Eh, writing a database versioning script would take a few hours at most, probably not worth the annoyance of including another external dependency. It's just a version number and dictionary of database-version to sql query. If the version doesn't match the last entry in the list, find it and execute all SQL queries between it and the end, update the version number in the database once done.

**Comment by liambaloh** [comment]
Ah okay! That makes it way more appealing. There are two concerns that came to mind though: 
- The first is just a general feeling that we'd be doing the database equivalent of using visual studio for something notepad could do, which isn't necessarily a bad thing, but it seems overkill to me... This concern can't really be taken away, so I won't dwell on it, but thought I'd mention it anyway. 
- The second is more of a technical problem: While the database structure could be migrated with this, we also use the config table to store key-value pairs, which would more commonly be implemented as an additional table with dozens of columns, with just one entry. We store the data as entries in a single table called configs though. So we'd need _some_ data migration, but definitely not other data migration.

Anyway, the way I make the migration files at the moment is by looking through the SQL history in MySQL Workbench (though we use MariaDB)

![image](https://user-images.githubusercontent.com/1364475/51283539-6dfa4e00-19e0-11e9-979a-2f8251f7ae9e.png)

**Comment by Denneledoe** [comment]
yes. code. mhmm, PHP
