### ISSUE TITLE
GET Parameter to hide Livestream

### ISSUE THREAD

**Issue by CrazyMatt** [OneHourGameJam/OneHourGameJam#52]
Perhaps we should have a GET parameter so that livestreamers can visit that link, or a "Hide the Stream" button to the link, and the livestream won't automatically start for that user.

**Comment by CrazyMatt** [comment]
Perhaps a button under the livestream would lead to this link?

**Comment by balohmatevz** [comment]
Added in https://github.com/OneHourGameJam/OneHourGameJam/commit/f037f94768c3130a56ee6dc40dedbdc907b7742a

The parameter is "shutup". example: http://onehourgamejam.com/?page=main&shutup=1
