### ISSUE TITLE
Add Titles to Pages

### ISSUE THREAD

**Issue by CrazyMatt** [OneHourGameJam/OneHourGameJam#53]
Change the title sent to the browser for each page (main, submit, profiles) for easy identification.

**Comment by balohmatevz** [comment]
With the head tag being moved from index.php into template/header.html, this can be done with a Mustache tag.

**Comment by balohmatevz** [comment]
Implemented in f6144a1d276465ef4f6cf79d15f10be7f824ef0f and 92a416742699858bc96d003d86910daf729680a8
