### ISSUE TITLE
Get a SSL certificate

### ISSUE THREAD

**Issue by patrickriordan** [OneHourGameJam/OneHourGameJam#56]
Http is not secure and it people can easily steal information sent over http.
The issue is that people often reuse passwords which means that all non-https password sites are the weakest link.

HTTPS please!

**Comment by balohmatevz** [comment]
A HTTPS certificate would require monetary investment on my part + some regular work. I do look into it every so often, but haven't yet done it. The site is hosted on a managed hosting server, where I only have CPanel access, meaning I can't use Let's Encrypt. 

At least I did as much as I could to protect the passwords at rest - they are salted with both a per-user salt and a site-wide salt and hashed a random number of times (between 10k and 20k times) using SHA256. The number of times is different for each user. I'm not using bcrypt so the site would work on PHP 5.4.

**Comment by patrickriordan** [comment]
@balohmatevz Makes sense. That at rest encryption sounds impressive!

This my first time doing 1 hour game jam and I really love the site! If I end up doing it more I would be happy to help with the hosting/cert stuff as well as costs if you're interested.

My VPS + hosting costs per year right now are:
$20 for cheap vps
$10 for domain name
apparently only additional $10 for cert

**Comment by mkalam-alami** [comment]
Since Let's Encrypt is not possible, another free alternative would be to use Cloudflare as a proxy.

**Comment by balohmatevz** [comment]
Done
