### ISSUE TITLE
Implement Sign in with Google / Firebase

### ISSUE THREAD

**Issue by CrazyMatt** [OneHourGameJam/OneHourGameJam#66]
Many users don't like remembering separate passwords or password managers, and it's a lot more convenient to use something like [Google Identity Platform](https://developers.google.com/identity/choose-auth), which allows multiple sign in options.

**Comment by liambaloh** [comment]
I'm not sure doing this is a good idea anymore. It seems as though OAuth and equivalents have gone out of fashion...
