### ISSUE TITLE
Add Request API

### ISSUE THREAD

**Issue by MrBigaston** [OneHourGameJam/OneHourGameJam#67]
Hello!
I think an basic read API (maybe with Node support) for get the Theme, the number of game, the number of game of a user can be nice.

Thanks ^^

**Comment by alyphen** [comment]
There is already a basic API in place, though I'm not sure it'll give you _everything_ you want right now.
User data: http://onehourgamejam.com/api/userdata/?username=alyphen
Next jam: http://onehourgamejam.com/api/nextjam/
(There are also endpoints at http://onehourgamejam.com/api/pollvote/ and http://onehourgamejam.com/api/themevote/ but they require you to be logged in and have IDs for the theme you want)

**Comment by MrBigaston** [comment]
Oh yes! I don't see that, thanks!
