### ISSUE TITLE
Better confirmation for game submissions

### ISSUE THREAD

**Issue by puarsliburf** [OneHourGameJam/OneHourGameJam#68]
It's hard to tell if your game has been successfully submitted to the site, a simple "Game Submitted" box would be enough

**Comment by balohmatevz** [comment]
I've added in-page confirmations for various events, including game submission, updates, deletion (admin only), jam addition, update, deletion, registering, logging in, asset addition, updating, etc.

![image](https://user-images.githubusercontent.com/1364475/40281033-50b93442-5c5c-11e8-9bf5-dc488d70952a.png)
