### ISSUE TITLE
Display who scheduled a jam (only visibl for other mods)

### ISSUE THREAD

**Issue by Laguna1989** [OneHourGameJam/OneHourGameJam#69]
It would be great to see who scheduled a jam.

**Comment by balohmatevz** [comment]
While looking at the sort of user data we keep I sort of noticed we don't actually log this anywhere at the moment 😅 

We store the IP and User Agent of the mod scheduling the jam though, so we could probably figgure out who scheduled any jam in particular unless the mod really wanted to hide themselves.

**Comment by balohmatevz** [comment]
This is now done. The "Manage Content" page will show who scheduled the jam.

![image](https://user-images.githubusercontent.com/1364475/40275180-9a1816d6-5be8-11e8-807b-62541005ef17.png)

On our deployment, I went through a few of the last jams and matched IPs to manually set who added them. I didn't go super far with this though. If anyone wants to play with this, here's the SQL:

```
SELECT jam_id, jam_jam_number, themevote_ip, themevote_username 
FROM ((jam j) LEFT JOIN (
 SELECT distinct tv.themevote_ip, tv.themevote_username
 FROM themevote tv
WHERE themevote_ip != "LEGACY" 
AND themevote_ip != ""
) a ON (j.jam_ip = a.themevote_ip))
```
