### ISSUE TITLE
Live streams promotion

### ISSUE THREAD

**Issue by vintprox** [OneHourGameJam/OneHourGameJam#86]
Sometimes stream looks like a key of 1HGJ! I see it's broken. By the way, what states we have?

- Not-a-time - time before jam and 3 hours after.
- Indetermined - waiting for stream approval.
- Streaming. Actually I think **there must be no limit to a single stream** - diversity is encouraged in open community!

In indetermined state some moderator can reject promotion of the staged volunteer's stream. By default any stream gonna get promotion.

The way we can promote the stream(s) without distraction is to place bar fixed at the bottom of window and announce stream with smooth shaky animation (button's chrome glow, vertical marquee like "Currently playing", etc.). The bar also appears on indetermined state to show that we didn't forget about our beloved audience!

There are actually many ways to show stream coming: see answers on question no. 3 of discussion in #89.

**Comment by liambaloh** [comment]
We already have live-stream promotion. A streamer whose username is entered in configuration will have their stream appear at the top of the main page while they stream. I like the rest of it though. To make this more manageable, I've broken this ticket down into two, as they don't depend on each other: #142 and #147
