### ISSUE TITLE
Progressive Web Application

### ISSUE THREAD

**Issue by vintprox** [OneHourGameJam/OneHourGameJam#88]
Meanwhile with some refactoring we could provide slightly better user experience with PWA replacing generic website. This guarantees least native look - like if there was no browser (once you added 1HGJ on home screen), but mobile application.

With all this said, there has to be some workaround to browsing stuff **offline**. Last seen jams, games and their developers' info should be accessible once you entered PWA with Internet connection and then lost it (with notification about possible obsoleteness of saved information).

**Comment by balohmatevz** [comment]
How would 1hgj benefit from being a PWA? I know they're the new hotness but I'm unsure of how we'd benefit from the technology...

**Comment by vintprox** [comment]
We can benefit from it by fostering community engagement out from native service features that are available for PWAs such as **notifications**. Just imagine how easy it would be for people to see jam countdown, evaluated theme, stream announcements, etc. without chat noise.
Also, PWA is designed with mobile users in mind, which is shared approach! It is performant, it doesn't close because your browser was too long in background. It is intended basically for everybody, but usually ignored (because browsers don't notify that you can add certain website to home screen - but hey, we surely can!).

There is good read about how companies benefit from PWAs: https://www.infoq.com/articles/progressive-web-app-benefits

**Comment by WetDesertRock** [comment]
The question is if the time to develop it as a PWA is worth the effort.

Better notifications? Web pages can do that (although you did cover it as less than optimal). We can also look into emailing, tweeting, or other forms of social media. In fact, social media is a great way to remind people because they can share and engage with it.

I'm just saying that perhaps the benefits can actually be found elsewhere in easier to develop ways.

**Comment by vintprox** [comment]
Social media is great while you are on the same page with them. PWA comes to the stage as fast-developed alternative of SMM bots. While notifications is not core point of actually designing such system, we think more about consistency it gives to the users that don't rely on social networks: somebody with awful connection at home, somebody who ultimately likes to switch between apps rather than websites and seeing it reload after *being in background*. Because you can't, for example, just list games' and developers' info in social network, because that's how pollution becomes real. By the way, website notifications could be utilized to make someone think: "Oh, new game appeared!" or "Great, another game from *this particular developer*!"

See? It's more about **personalization**. If you don't recognize the importance of this task, why ever care about the effort that is gonna be little?

**Comment by Laguna1989** [comment]
I have no experience as a WebDev, but I take part in 1hgj for more than three years now. Looking up the countdown on the webpage or on discord/irc was never an issue for me. Notifications are sent out over discord/Twitter automatically. This is working because those are the places people are already at and use frequently. Why create _yet another_ channel of communication which people have to check for  when they want some information.

This sounds like a massive lets use #new_feature because it is #new_feature and #hot. Has anyone thought about putting 1hgj to the blockchain recently? Actually, why are we not already doing crycptosecurity-enhanced machine learning and 1hgj wearables? /s

**Comment by vintprox** [comment]
@Laguna1989 confusing offtop. Can't you just say something against the points I made clear (some are highlighted) in my last comments here?

**Comment by mkalam-alami** [comment]
I too think that the community doesn't need PWA features that much (offline browsing, app notifications etc.) After all, we're mostly browsing the site around jam times, when we have to code a game from our computers.

The bigger concern (that peeked behind Laguna's sarcasm) is you're suggesting a major shift to the site philosophy: 1HGJ currently has a PC-first UI on a straightforward PHP/MySQL/Server-side rendering stack, and it barely uses JS. It was clearly not designed for PWA support.

Personally I wouldn't mind you hacking a little something, but anything with a major impact on the code would mean that all the long-term devs (...well, Liam) would have to maintain it, and start being careful not to break PWA support, test the site on their mobiles etc. It would not seem worth it to me.

**Comment by vintprox** [comment]
Oh, I see. It's not much of overhead when something new is covered by *unit tests*, I swear.
I'm looking forward to provide accessibility for everyone without persistent computer thing. There is something more than just code in games, and some team members (#62) cannot be bound to non-pocket hardware. So with PWA they basically can switch and see information faster, because WebView there doesn't unload on accident. There is still plenty to add for teams on website, like a manual for collaboration, code of conduct, commitment invitations (good first projects, why not?).

Or website is supposed to stay just the collection of entries? I'm sorry if I don't see a reason for that legacy, but project's scale is viable for enhancements like PWA - to stop limiting audience to PC and pationately-waiting-to-reload-on-mobile-browser-sixty-times-per-hour.

> philosophy

I don't buy it. It needs some change, just since the beginning. I'm polling people what they think, and most of them they react with welcoming. Rendering and processing stuff is not bothering them, but main concern is a speed, so there is clearly no huge reason to play with slow backend stack and machine another 3 years. I will help solving this.
