### ISSUE TITLE
Theme preview generator

### ISSUE THREAD

**Issue by vintprox** [OneHourGameJam/OneHourGameJam#90]
I was thinking about **visual representation of any announced theme** and came to my most beloved solution:

1. automatically find some images by theme using Unsplash open API,
2. provide those for voting in discord admin channel or website admin section,
3. summarize the common choice,
4. resize chosen image, apply filters matching the website color scheme and branding to it,
5. set as official preview of the theme,
6. automagically credit the author of photography/artwork in side info.

Preview then can be used as background for section dedicated to specific theme or as preview of upcoming stream (see also: #86)!

**Comment by liambaloh** [comment]
I don't really see much value from this. It'd introduce risk of picking mislabeled inappropriate content as well as copyrighted content. And I see basically no benefit from it.

While adding an option to add an image while scheduling a jam for admins to provide an image to go with the theme could avoid a lot of this risk, I don't think the automated parts could offer much value...
