### ISSUE TITLE
Site does not show errors, warnings and success messages

### ISSUE THREAD

**Issue by liambaloh** [OneHourGameJam/OneHourGameJam#93]
Site used to perform the action and then render the page, this was changed to actions being performed first, followed by a redirect after the action in 3dc311b2bf15cebbe1ba5b1f8c2b2525275163a7

This means that existing calls to functions like AddWarning(), AddError() and AddSuccess() in https://github.com/OneHourGameJam/OneHourGameJam/blob/master/php/warnings.php are lost after the page redirect after the action concludes.

**Comment by winniehell** [comment]
I assume we want to keep the redirect as is, correct?

Storing the message on the client side (cookie / localstorage) would mean that it's shown in different browser tabs, too.

So the only solution I see, would be to append a parameter to the redirection URL. For example `?page=main&message=submit_game_success` and then something like

```php
if ($_GET["message" === "submit_game_success"]) {
?>
  You have successfully submitted a game.
```

Does that make sense?

**Comment by liambaloh** [comment]
I think that's a good idea! I was stuck with the cookie solution for a few days, but unhappy with that, but adding it to the URL could work. The URL could even be cleared with javascript, to hide the extra get parameter, so it doesn't get copy-pasted by accident.
